version: "3.8"

volumes:
  mongodb_data:

services:
  bot:
    image: rust:1.75-slim
    container_name: bot
    working_dir: /app
    volumes:
      - ./.env:/app/.env
      - ./target/release:/app
      - ./files:/app/files
    command: bash -c "mkdir -p ./files/anon && ./app"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
