name: "New Release"

permissions:
  contents: "write"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  repo-lower:
    name: "Lowercase Repository Name"
    runs-on: "ubuntu-latest"
    outputs:
      repo: ${{ steps.repo.outputs.REPO }} 
      repo-name: ${{ steps.repo-name.outputs.REPO_NAME }} 
    steps:
      - name: "Checkout The Repository"
        uses: actions/checkout@v4.1.1

      # echo "REPO=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_OUTPUT
      # echo "REPO=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      - name: "Lowercase github.repository"
        id: "repo"
        shell: "bash"
        run: |
          echo "REPO=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_OUTPUT

      - name: "Lowercase github.event.repository.name"
        id: "repo-name"
        shell: "bash"
        run: |
          echo "REPO_NAME=`echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_OUTPUT

  get-tag:
    name: "Get Tag From Package Version"
    runs-on: "ubuntu-latest"
    outputs:
      pkg-version: ${{ steps.pkg-version.outputs.PKG_VERSION }} 
    steps:
      - name: "Checkout The Repository"
        uses: actions/checkout@v4.1.1

      - name: "Get tag"
        id: "pkg-version"
        shell: "bash"
        run: |
          echo PKG_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml) >> $GITHUB_OUTPUT

  create-release:
    name: "Create release"
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: "get-tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout The Repository"
        uses: actions/checkout@v4.1.1
      
      - name: "Create release"
        uses: "taiki-e/create-gh-release-action@v1"
        with:
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Select the branch and tag
          branch: "main"
          ref: refs/tags/v${{ needs.get-tag.outputs.pkg-version }}

  upload-assets:
    name: "Upload assets to Github releases"
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: 
      - "repo-lower"
      - "get-tag"
      - "create-release"
    strategy:
      matrix:
        fail-fast: false
        matrix:
          platform:
            - linux/arm64
            - linux/amd64
            # - linux/arm/v6
            # - linux/arm/v7
        # include:
        #   - target: "x86_64-unknown-linux-gnu"
        #     os: "ubuntu-latest"
        #   # - target: "x86_64-unknown-linux-musl"
        #   #   os: "ubuntu-latest"
        #   # - target: "aarch64-unknown-linux-musl"
        #   #   os: "ubuntu-latest"
        #   # - target: "aarch64-unknown-linux-musl"
        #   #   os: "ubuntu-latest"
    runs-on: ${{ matrix.platform }}
    # runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout The Repository"
        uses: actions/checkout@v4.1.1

      - name: Install OpenSSL
        run: sudo apt-get install -y pkg-config libssl-dev

      - name: "Upload Binaries"
        uses: "taiki-e/upload-rust-binary-action@v1"
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: ${{ needs.repo-lower.outputs.repo-name }}
          # (optional) Target triple, default is host triple.
          target: ${{ matrix.target }}
          # (optional) Archive name (non-extension portion of filename) to be uploaded.
          # [default value: $bin-$target]
          # [possible values: the following variables and any string]
          #   variables:
          #     - $bin    - Binary name (non-extension portion of filename).
          #     - $target - Target triple.
          #     - $tag    - Tag of this release.
          # When multiple binary names are specified, default archive name or $bin variable cannot be used.
          archive: $bin-${{ matrix.target }}
          # Select the tag
          ref: refs/tags/v${{ needs.get-tag.outputs.pkg-version }}
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  push-to-registry:
    name: "Push Docker image to GHCR"
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - "repo-lower"
      - "get-tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout The Repository"
        uses: actions/checkout@v4.1.1

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3.0.0

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3.0.0

      - name: "Login to GitHub Container Registry (GHCR)"
        uses: docker/login-action@v3.0.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
          # password: ${{ github.token }}

      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@v5.5.0"
        with:
          images: ghcr.io/${{ needs.repo-lower.outputs.repo }}

      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v5.1.0"
        with:
          context: .
          # file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          # platforms: linux/amd64, linux/arm64/v8
          # tags: ${{ needs.repo-lower.outputs.repo }}:latest,${{ needs.repo-lower.outputs.repo }}:v${{ needs.get-tag.outputs.pkg-version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
